export const TAXONOMY_VERSION = 3;

const single = (categoryId) => [categoryId];

export const SOURCE_CATEGORY_PROJECTIONS = {
  // 新闻：把长期被“综合”吞掉的媒体来源还原到稳定新闻域。
  toutiao: single("news-domestic"),
  "qq-news": single("news-domestic"),
  "netease-news": single("news-domestic"),
  "sina-news": single("news-domestic"),
  thepaper: single("news-domestic"),
  sina: single("news-domestic"),
  "zhihu-daily": single("news-depth"),
  nytimes: single("news-world"),
  "bbc-world": single("news-world"),
  "guardian-world": single("news-world"),
  "nhk-news": single("news-world"),
  aljazeera: single("news-world"),
  "npr-news": single("news-world"),
  "dw-news": single("news-world"),
  "france24-fr": single("news-world"),
  lemonde: single("news-world"),
  elpais: single("news-world"),
  yonhap: single("news-world"),
  timesofindia: single("news-world"),
  "cbc-news": single("news-world"),
  "abc-au-news": single("news-world"),
  "rnz-news": single("news-world"),

  // 科技：按用户心智拆成数码、产业、开发者、科学、设计。
  ithome: single("tech-digital"),
  coolapk: single("tech-digital"),
  sspai: single("tech-digital"),
  dgtle: single("tech-digital"),
  ifanr: single("tech-digital"),
  geekpark: single("tech-digital"),
  theverge: single("tech-digital"),
  arstechnica: single("tech-digital"),
  wired: single("tech-digital"),
  "apple-app-store": single("tech-digital"),
  "xiaomi-app-store": single("tech-digital"),
  "yingyongbao-store": single("tech-digital"),
  "oppo-app-store": single("tech-digital"),
  "antutu-rankings": single("tech-digital"),
  "zol-phone-rankings": single("tech-digital"),
  "zol-tech-rankings": single("tech-digital"),
  "pconline-rankings": single("tech-digital"),
  "ludashi-rankings": single("tech-digital"),
  "36kr": single("tech-industry"),
  huxiu: single("tech-industry"),
  producthunt: single("tech-industry"),
  techcrunch: single("tech-industry"),
  csdn: single("tech-developer"),
  juejin: single("tech-developer"),
  github: single("tech-developer"),
  hackernews: single("tech-developer"),
  hellogithub: single("tech-developer"),
  "51cto": single("tech-developer"),
  lobsters: single("tech-developer"),
  devto: single("tech-developer"),
  "github-blog": single("tech-developer"),
  "stackoverflow-blog": single("tech-developer"),
  infoq: single("tech-developer"),
  "chrome-web-store": single("tech-developer"),
  "vscode-marketplace": single("tech-developer"),
  "greasy-fork": single("tech-developer"),
  krebsonsecurity: single("tech-developer-security"),
  thehackernews: single("tech-developer-security"),
  "google-security": single("tech-developer-security"),
  guokr: single("tech-science"),
  "nasa-news": single("tech-science"),
  "nature-news": single("tech-science"),
  sciencenews: single("tech-science"),
  smashing: single("tech-design"),
  dezeen: single("tech-design"),

  // 文娱：修正此前误放生活/综合的来源。
  "douban-movie": single("entertainment-video-movie"),
  weread: single("entertainment-reading-books"),
  bilibili: single("entertainment-video"),
  acfun: single("entertainment-video"),

  // 游戏：来源平台按职责落位，折扣同时投影到生活优惠。
  gameres: single("games-content"),
  yystv: single("games-content"),
  eurogamer: single("games-content"),
  miyoushe: single("games-community"),
  ngabbs: single("games-community"),
  lol: single("games-esports"),
  "taptap-games": single("games-ranking"),
  "bilibili-game-rankings": single("games-ranking"),
  "huya-video-rankings": single("games-ranking"),
  "lol-top-canyon": single("games-esports"),
  "ithome-xijiayi": ["games-deals", "life-deals"],
  "steam-deals": ["games-deals", "life-deals"],
  "epic-free-games": ["games-deals", "life-deals"],
  "xiaoheihe-deals": ["games-deals", "life-deals"],
  ggdeals: ["games-deals", "life-deals"],
  "gog-deals": ["games-deals", "life-deals"],

  // 生活与优惠：“羊毛”不再作为一级领域，统一落到生活 → 优惠省钱。
  "super-deals": single("life-deals"),
  "0818tuan": single("life-deals"),
  "nodeloc-deals": ["life-deals", "community-tech"],
  smzdm: single("life-deals"),
  "autohome-sales": single("life-auto"),
  weatheralarm: single("life-public"),
  earthquake: single("life-public"),
  history: single("life-education"),
  "who-news": single("life-health"),

  // 社区：继续作为高意图导航生态，但细分并允许与领域交叉。
  tieba: single("community-general"),
  zhihu: single("community-general"),
  "douban-group": single("community-interest"),
  jianshu: single("community-general"),
  hupu: ["community-interest", "sports-general"],
  v2ex: ["community-tech", "tech-developer"],
  "52pojie": ["community-tech", "tech-developer"],
  hostloc: ["community-tech", "tech-developer"],
  linuxdo: ["community-tech", "tech-developer"],
  nodeseek: ["community-tech", "tech-developer"],
  tianya: single("community-general"),
  newsmth: single("community-general"),
  "hatena-hot": single("community-general"),
};

export const VARIANT_CATEGORY_PROJECTIONS = [
  { id: "qq-news-entertainment", sourceName: "qq-news", variant: "entertainment", label: "娱乐热点榜", categoryIds: ["entertainment"] },
  { id: "qq-news-sports", sourceName: "qq-news", variant: "sports", label: "体育热点榜", categoryIds: ["sports-general"] },
  { id: "douyin-entertainment", sourceName: "douyin", variant: "entertainment", label: "娱乐榜", categoryIds: ["entertainment"] },
  { id: "douyin-society", sourceName: "douyin", variant: "society", label: "社会榜", categoryIds: ["news-domestic"] },
  { id: "bilibili-music", sourceName: "bilibili", variant: "music", label: "全站音乐榜", categoryIds: ["entertainment-music-songs"] },
  { id: "baidu-novel", sourceName: "baidu", variant: "novel", label: "小说榜", categoryIds: ["entertainment-reading-novels"] },
  { id: "baidu-movie", sourceName: "baidu", variant: "movie", label: "电影榜", categoryIds: ["entertainment-video-movie"] },
  { id: "baidu-teleplay", sourceName: "baidu", variant: "teleplay", label: "电视剧榜", categoryIds: ["entertainment-video-tv"] },
  { id: "baidu-car", sourceName: "baidu", variant: "car", label: "汽车榜", categoryIds: ["life-auto"] },
  { id: "baidu-game", sourceName: "baidu", variant: "game", label: "游戏榜", categoryIds: ["games-ranking"] },
];

export const getProjectedSourceCategoryIds = (sourceName, fallback = []) =>
  SOURCE_CATEGORY_PROJECTIONS[sourceName]?.slice() || fallback.slice();
